# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: backdoor_test_user
          POSTGRES_DB: backdoor_test
          POSTGRES_PASSWORD: "test"
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-v2-{{ checksum "framework/project/plugins.sbt" }}-{{ checksum "framework/build.sbt" }}-{{ checksum "sbt-plugin/project/plugins.sbt" }}-{{ checksum "sbt-plugin/build.sbt" }}
          - dependencies-v2
      - restore_cache:
          keys:
          - node-modules-v2-{{ checksum "framework/package.json" }}
          - node-modules-v2
      - restore_cache:
          keys:
          - target-v2-{{ .Branch }}
          - target-v2

      - run: cd framework && yarn install
      - run: cd framework && sbt coverage test coverageReport
      - run: cd sbt-plugin && sbt test
      - run: sbt coverageAggregate
      - run: bash <(curl -s https://codecov.io/bash) -Z
      - save_cache:
          paths:
            - framework/node_modules
          key: node-modules-v1-{{ checksum "framework/package.json" }}
      - save_cache:
          paths:
            - framework/target
            - sbt-plugin/target
          key: target-v2-{{ .Branch }}
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: dependencies-v2-{{ checksum "framework/project/plugins.sbt" }}-{{ checksum "framework/build.sbt" }}-{{ checksum "sbt-plugin/project/plugins.sbt" }}-{{ checksum "sbt-plugin/build.sbt" }}
      - store_artifacts:
          path: /tmp/screenshots
